apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-store-fe
  namespace: item-store
  labels:
    app: item-store-fe
spec:
  selector:
    matchLabels:
      app: item-store-fe
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: item-store-fe
    spec:
      containers:
      - name: item-store-fe
        image: jeffersfp/items-frontend:0.1.0
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 3000
          name: item-store-fe
      restartPolicy: Always
