# kustomization file for the local backend overlay from ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

# set custom tag for the image
images:
  - name: item-store-be
    newTag: 0.1.1-develop-1234

replicas:
  - name: item-store-be
    count: 2
