# kustomization file for the local backend overlay from ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

replicas:
  - name: item-store-be
    count: 3
