apiVersion: v1
kind: Service
metadata:
  name: item-store-be
  namespace: item-store
spec:
  selector:
    app: item-store-be
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
