name: Deploy to PROD

on:
  push:
    branches:
      - main

jobs:
jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml
  test:
    uses: ./.github/workflows/_test.yaml
  build:
    uses: ./.github/workflows/_build.yaml
    needs:
      - lint
      - test
  deploy:
    uses: ./github/workflows/lib/deploy.yaml
    needs: build
